name: github.action
channels:
    - default
    - https://conda.anaconda.org/conda-forge/
    - https://conda.anaconda.org/joshburt/
dependencies:
  - anaconda-project
  - conda-build
  - conda-verify
  - setuptools
  - anaconda-client
